### ISSUE TITLE
Failed to run 'python3 makeweb.py'

### ISSUE THREAD

**Issue by hwhsu1231** [swig/www#13]
### Problem Description

Hello, Swig Development Team.

Recently, I tried to run `python3 makeweb.py` to build a complete website locally. However, it failed with the following error messages. What happened?

```bash
Traceback (most recent call last):
  File "/media/hwhsu1231/Data/Test/www/makeweb.py", line 121, in <module>
    html_string = subprocess.check_output(["php", php_filename])
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'php'
```

The following is the full logs:

<details><summary>Click to expand full logs</summary>

```bash
hwhsu1231@vb-kubuntu:/media/hwhsu1231/Data/Test$ git clone https://github.com/swig/www.git
Cloning into 'www'...
remote: Enumerating objects: 2683, done.
remote: Counting objects: 100% (145/145), done.
remote: Compressing objects: 100% (108/108), done.
remote: Total 2683 (delta 53), reused 107 (delta 36), pack-reused 2538
Receiving objects: 100% (2683/2683), 62.39 MiB | 2.53 MiB/s, done.
Resolving deltas: 100% (1749/1749), done.
hwhsu1231@vb-kubuntu:/media/hwhsu1231/Data/Test$ cd www
hwhsu1231@vb-kubuntu:/media/hwhsu1231/Data/Test/www$ python makeweb.py
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
hwhsu1231@vb-kubuntu:/media/hwhsu1231/Data/Test/www$ which python
hwhsu1231@vb-kubuntu:/media/hwhsu1231/Data/Test/www$ which python3
/usr/bin/python3
hwhsu1231@vb-kubuntu:/media/hwhsu1231/Data/Test/www$ python3 makeweb.py
Wrote donate.html
Wrote download.html
Wrote exec.html
Wrote faq.html
Wrote future.html
Wrote guilty.html
Wrote history.html
Wrote legal.html
Wrote links.html
Wrote mail.html
Wrote myths.html
Wrote nsf.html
Wrote projects.html
Wrote propaganda.html
Wrote rants.html
Wrote release.html
Wrote screenshot.html
Wrote screenshot2.html
Wrote survey.html
Wrote surveyresults.html
Wrote svn.html
Wrote tutorial.html
Wrote y2k.html
Wrote article_cpp.html
Wrote bugs.html
Wrote compare.html
Wrote compat.html
Wrote cpp.html
Wrote doc.html
Wrote news.php
Traceback (most recent call last):
  File "/media/hwhsu1231/Data/Test/www/makeweb.py", line 121, in <module>
    html_string = subprocess.check_output(["php", php_filename])
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'php'
hwhsu1231@vb-kubuntu:/media/hwhsu1231/Data/Test/www$
```

</details>

**Comment by wsfulton** [comment]
Fixed by 7d0f2e4597bbb20d37527e4043f2dbd364a47c8d.

**Comment by hwhsu1231** [comment]
@wsfulton I tried to run `git clone` and `python3 makeweb.py`, but the same error still occurred:

<details><summary>Click to expand full logs</summary>

```bash
hwhsu1231@vb-kubuntu:~/Repo$ git clone https://github.com/swig/www.git
Cloning into 'www'...
remote: Enumerating objects: 2738, done.
remote: Counting objects: 100% (200/200), done.
remote: Compressing objects: 100% (151/151), done.
remote: Total 2738 (delta 94), reused 136 (delta 48), pack-reused 2538
Receiving objects: 100% (2738/2738), 65.62 MiB | 4.00 MiB/s, done.
Resolving deltas: 100% (1790/1790), done.
hwhsu1231@vb-kubuntu:~/Repo$ cd www
hwhsu1231@vb-kubuntu:~/Repo/www$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
hwhsu1231@vb-kubuntu:~/Repo/www$ git log -1
commit 127a91b2a941b334468f4273a5eae0778a3815fa (HEAD -> master, origin/master, origin/HEAD)
Author: William S Fulton <wsf@fultondesigns.co.uk>
Date:   Sat Dec 30 23:42:22 2023 +0000

    Add Javascript Node-API (formerly NAPI) link
hwhsu1231@vb-kubuntu:~/Repo/www$ python3 makeweb.py
Wrote y2k.html
Wrote surveyresults.html
Wrote history.html
Wrote bugs.html
Wrote cpp.html
Wrote rants.html
Wrote links.html
Wrote faq.html
Wrote projects.html
Wrote compare.html
Wrote screenshot.html
Wrote future.html
Wrote nsf.html
Wrote download.html
Wrote propaganda.html
Wrote survey.html
Wrote doc.html
Wrote compat.html
Wrote donate.html
Wrote guilty.html
Wrote legal.html
Wrote svn.html
Wrote myths.html
Wrote tutorial.html
Wrote screenshot2.html
Wrote exec.html
Wrote article_cpp.html
Wrote mail.html
Wrote release.html
Wrote index.php
Traceback (most recent call last):
  File "/home/hwhsu1231/Repo/www/makeweb.py", line 121, in <module>
    html_string = subprocess.check_output(["php", php_filename])
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'php'
hwhsu1231@vb-kubuntu:~/Repo/www$
```

</details>

What did I miss?

**Comment by wsfulton** [comment]
Sorry, I got mixed up, https://github.com/swig/www/commit/7d0f2e4597bbb20d37527e4043f2dbd364a47c8d is for python 3 support. You are missing php, that should be clear from the error message.

**Comment by hwhsu1231** [comment]
So how could I solve this 'php' missing message? Am I supposed to run `pip install php` first? But it still failed with the same error:

<details><summary>Click to expand full logs</summary>

```bash
hwhsu1231@vb-kubuntu:~/Repo/www$ pip install php
Defaulting to user installation because normal site-packages is not writeable
Collecting php
  Downloading php-1.2.1.tar.gz (4.2 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: php
  Building wheel for php (setup.py) ... done
  Created wheel for php: filename=php-1.2.1-py3-none-any.whl size=4395 sha256=d62df3cbd353bed6d37a540a1eb9c9ab96a42215558913774a7ae3d58e041a00
  Stored in directory: /home/hwhsu1231/.cache/pip/wheels/42/1d/01/57ca0d0a8d315d72b4868fd3cb7becc82f029780fb77c4acc4
Successfully built php
Installing collected packages: php
Successfully installed php-1.2.1
hwhsu1231@vb-kubuntu:~/Repo/www$ python3 makeweb.py
Wrote y2k.html
Wrote surveyresults.html
Wrote history.html
Wrote bugs.html
Wrote cpp.html
Wrote rants.html
Wrote links.html
Wrote faq.html
Wrote projects.html
Wrote compare.html
Wrote screenshot.html
Wrote future.html
Wrote nsf.html
Wrote download.html
Wrote propaganda.html
Wrote survey.html
Wrote doc.html
Wrote compat.html
Wrote donate.html
Wrote guilty.html
Wrote legal.html
Wrote svn.html
Wrote myths.html
Wrote tutorial.html
Wrote screenshot2.html
Wrote exec.html
Wrote article_cpp.html
Wrote mail.html
Wrote release.html
Wrote index.php
Traceback (most recent call last):
  File "/home/hwhsu1231/Repo/www/makeweb.py", line 121, in <module>
    html_string = subprocess.check_output(["php", php_filename])
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'php'
hwhsu1231@vb-kubuntu:~/Repo/www$
```

</details>

**Comment by hwhsu1231** [comment]
@wsfulton All right! After running the following command to install php on Kubuntu, the problem is solved.

```
sudo apt install php
```

<details><summary>Click to expand full logs</summary>

```bash
hwhsu1231@vb-kubuntu:~/Repo/www$ python3 makeweb.py
Wrote y2k.html
Wrote surveyresults.html
Wrote history.html
Wrote bugs.html
Wrote cpp.html
Wrote rants.html
Wrote links.html
Wrote faq.html
Wrote projects.html
Wrote compare.html
Wrote screenshot.html
Wrote future.html
Wrote nsf.html
Wrote download.html
Wrote propaganda.html
Wrote survey.html
Wrote doc.html
Wrote compat.html
Wrote donate.html
Wrote guilty.html
Wrote legal.html
Wrote svn.html
Wrote myths.html
Wrote tutorial.html
Wrote screenshot2.html
Wrote exec.html
Wrote article_cpp.html
Wrote mail.html
Wrote release.html
Wrote index.php
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12289    0 12289    0     0  37129      0 --:--:-- --:--:-- --:--:-- 37239
Cache unable to open file for writing: ./cache/c7622d6337e25c345e9c210c8c01de3b
Wrote index.html
Wrote news.php
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 66204    0 66204    0     0   200k      0 --:--:-- --:--:-- --:--:--  200k
Cache unable to open file for writing: ./cache/00322df0eb00de09ad1fec5129fba79c
Wrote news.html
hwhsu1231@vb-kubuntu:~/Repo/www$ 
```

</details>

However, I wonder whether it is fine for this message:

```
Cache unable to open file for writing: ./cache/00322df0eb00de09ad1fec5129fba79c
```
